Add a drawer layout to memoriesfragement
MrTheGood/projectb_android pull request #60
Opened 2019-05-15 22:03 UTC by Hicham010

I added the DrawerLayout it isn't working yet, so be carefull Mates

2019-05-15 22:16 UTC, MrTheGood requested changes
Does not work. Trying to help, but this PR should NOT be accepted yet.

2019-05-15 23:06 UTC, MrTheGood commented
I fixed the issue. **Do not forget to pull.**

The issue: 
in `MainActivity` we have the `NavHostFragment` view, in which all `Fragment`s are shown. This `NavHostFragment` did not have `layout_height` to `match_parent` and `DrawerLayout` apparently didn't like it. I cheated it a bit with some brute force (and lube) and now it works.


However, **This pull request should not be accepted yet as it's clearly not done.**

2019-05-16 11:56 UTC, MrTheGood requested changes
This is clearly still unfinished.

2019-05-16 11:56 UTC, MrTheGood commented on app/src/main/res/values-nl/strings.xml
> +    <string name="close">close</string>
"close" is not a correct dutch translation.

2019-05-16 11:56 UTC, MrTheGood commented on app/src/main/res/menu/nav_menu.xml
> +</menu>
These items don't make sense.

2019-05-20 15:14 UTC, MrTheGood approved these changes
![proxy duckduckgo-1](https://user-images.githubusercontent.com/23239376/58032563-2537da80-7b23-11e9-84b1-6b1b2cd03680.jpg)

2019-05-20 15:17 UTC, Almightywesley approved these changes
Hicham this task was harder that we expected, but after our feedback and our help you finalu dit it. nice work! thumps up

2019-05-20 15:17 UTC, merged